services:
  - type: web
    name: blueinkhouse
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blueinkhouse.wsgi:application --preload"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: blueinkhouse.settings
